from dataclasses import dataclass
from typing import List, Optional, Dict, Any
import logging

logger = logging.getLogger(__name__)


@dataclass
class GenerationResult:
    answer: str
    context: str
    sources: List[Dict[str, Any]] = None
    metadata: Dict[str, Any] = None

    def __post_init__(self):
        if self.sources is None:
            self.sources = []
        if self.metadata is None:
            self.metadata = {}


class LLM:
    """Local LLM wrapper supporting vLLM and HuggingFace."""

    def __init__(
        self,
        endpoint: str = "http://localhost:8000/v1",
        model_name: str = "llama-3-8b",
        max_tokens: int = 512,
        temperature: float = 0.0,
    ):
        self.endpoint = endpoint
        self.model_name = model_name
        self.max_tokens = max_tokens
        self.temperature = temperature
        self._client = None

    @property
    def client(self):
        if self._client is None:
            try:
                from openai import OpenAI

                # Increased timeout to 300s to accommodate local model loading/inference
                self._client = OpenAI(
                    base_url=self.endpoint, 
                    api_key="dummy",
                    timeout=300.0
                )
            except Exception as e:
                logger.warning(f"Failed to initialize OpenAI client: {e}")
        return self._client

    def generate(
        self,
        prompt: str,
        retrieved_docs: Optional[List[Any]] = None,
        context: Optional[str] = None,
    ) -> GenerationResult:
        from generation.prompts import DEFAULT_SYSTEM_PROMPT

        # Format context with Source [breadcrumb] and [URL] markers
        if retrieved_docs:
            formatted_context = "\n\n".join(
                [
                    f"Source [{doc.metadata.get('breadcrumb', 'Unknown')}] (URL: {doc.metadata.get('source_url', 'N/A')}): {doc.text}"
                    for doc in retrieved_docs
                ]
            )
        else:
            formatted_context = context or "No context provided."

        system_content = DEFAULT_SYSTEM_PROMPT.format(context=formatted_context)

        user_content = prompt

        try:
            response = self.client.chat.completions.create(
                model=self.model_name,
                messages=[
                    {"role": "system", "content": system_content},
                    {"role": "user", "content": user_content},
                ],
                max_tokens=self.max_tokens,
                temperature=self.temperature,
                stream=False
            )
            answer = response.choices[0].message.content

            sources = []
            if retrieved_docs:
                    sources = [
                    {
                        "breadcrumb": doc.metadata.get("breadcrumb", "Unknown"),
                        "filename": doc.metadata.get("source", "Unknown"),
                        "page": doc.metadata.get("page_number", "Unknown"),
                        "url": doc.metadata.get("source_url"),
                    }
                    for doc in retrieved_docs
                ]

            return GenerationResult(
                answer=answer, context=formatted_context, sources=sources
            )
        except Exception as e:
            logger.error(f"LLM generation failed: {e}")
            return GenerationResult(
                answer="Error generating response",
                context=formatted_context,
                sources=[],
            )

    def generate_stream(
        self,
        prompt: str,
        retrieved_docs: Optional[List[Any]] = None,
        context: Optional[str] = None,
    ):
        """Yield tokens as they are generated by the LLM."""
        from generation.prompts import DEFAULT_SYSTEM_PROMPT

        if retrieved_docs:
            formatted_context = "\n\n".join(
                [
                    f"Source [{doc.metadata.get('breadcrumb', 'Unknown')}] (URL: {doc.metadata.get('source_url', 'N/A')}): {doc.text}"
                    for doc in retrieved_docs
                ]
            )
        else:
            formatted_context = context or "No context provided."

        system_content = DEFAULT_SYSTEM_PROMPT.format(context=formatted_context)

        try:
            stream = self.client.chat.completions.create(
                model=self.model_name,
                messages=[
                    {"role": "system", "content": system_content},
                    {"role": "user", "content": prompt},
                ],
                max_tokens=self.max_tokens,
                temperature=self.temperature,
                stream=True
            )
            for chunk in stream:
                if chunk.choices[0].delta.content:
                    yield chunk.choices[0].delta.content
        except Exception as e:
            logger.error(f"LLM streaming failed: {e}")
            yield f"\n[Error: {e}]"

    def batch_generate(
        self, prompts: List[str], contexts: Optional[List[str]] = None
    ) -> List[GenerationResult]:
        if contexts is None:
            contexts = [None] * len(prompts)

        results = []
        for prompt, ctx in zip(prompts, contexts):
            results.append(self.generate(prompt, context=ctx))
        return results

    def get_confidence_score(
        self,
        query: str,
        retrieved_docs: List[Any],
    ) -> float:
        """Rate how well the retrieved docs can answer the query (0 to 1)."""
        from generation.prompts import CONFIDENCE_CHECK_PROMPT
        import re

        # Fast path if no docs
        if not retrieved_docs:
            return 0.0

        formatted_context = "\n\n".join(
            [f"[{i+1}] {doc.text}" for i, doc in enumerate(retrieved_docs)]
        )

        prompt = CONFIDENCE_CHECK_PROMPT.format(
            query=query, context=formatted_context
        )

        try:
            # We use very low max_tokens and temperature for speed/consistency
            response = self.client.chat.completions.create(
                model=self.model_name,
                messages=[
                    {"role": "user", "content": prompt},
                ],
                max_tokens=10,
                temperature=0.0,
            )
            raw_output = response.choices[0].message.content.strip()
            
            # Extract number using regex (handles "Score: 0.8" or "0.8")
            match = re.search(r"(\d+\.?\d*)", raw_output)
            if match:
                score = float(match.group(1))
                return max(0.0, min(1.0, score))
            
            logger.warning(f"Could not parse confidence score from: {raw_output}")
            return 0.5  # Neutral fallback
            
        except Exception as e:
            logger.error(f"Confidence check failed: {e}")
            return 0.5
